# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import file_upload_pb2 as file__upload__pb2


class UploadStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Upload = channel.stream_unary(
        '/fileupload.Upload/Upload',
        request_serializer=file__upload__pb2.DataChunks.SerializeToString,
        response_deserializer=file__upload__pb2.UploadStatus.FromString,
        )


class UploadServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Upload(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UploadServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Upload': grpc.stream_unary_rpc_method_handler(
          servicer.Upload,
          request_deserializer=file__upload__pb2.DataChunks.FromString,
          response_serializer=file__upload__pb2.UploadStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fileupload.Upload', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
